var xhrMessagePage;initSelect2();activeInNavbar();function activeInNavbar(){var url=window.location.href;var base=$('base').attr('href');var urlCompleteLink='';$('#sidebar-menu a').each(function(){urlCompleteLink=base+$(this).attr('href');if(url==urlCompleteLink){$(this).addClass('active');if($(this).parents('.has_sub').length>0){$(this).parents('.has_sub').addClass('active');$(this).parents('.has_sub').find('.link-father-sub').addClass('active');$(this).parents('.has_sub').find('.list-unstyled').addClass('active');$(this).parents('.has_sub').find('.list-unstyled').show();$(this).parent('li').addClass('active').addClass('subdrop');}}});}
function appendFormTokenInput(form){return;}
$.validator.setDefaults({errorElement:"span",errorClass:"text-danger error-validate",errorPlacement:function(error,element){error.appendTo(element.parents('.form-group'));if(element.hasClass("summernote")){error.insertAfter(element.siblings(".note-editor"));}},highlight:function(element){if(!$(element).closest('.form-group').hasClass('has-feedback')){$(element).closest('.form-group').addClass('has-feedback')}
$(element).closest('.form-group').removeClass('has-success').addClass('has-error');$(element).closest('.form-group').find('.icon-validate-custom').remove();if($(element).closest('.form-group').find('input[type="text"],input[type="email"],input[type="password"],input[type="file"]').length){var classAdd='';if($(element).closest('.form-group').find('label').length==0){classAdd='input-without-label';}
$(element).closest('.form-group').append('<span class="icon-validate-custom fa fa-remove form-control-feedback '+classAdd+'"></span>');}},unhighlight:function(element){if(!$(element).closest('.form-group').hasClass('has-feedback')){$(element).closest('.form-group').addClass('has-feedback');}
$(element).closest('.form-group').removeClass('has-error').addClass('has-success');$(element).closest('.form-group').find('.icon-validate-custom').remove();if($(element).closest('.form-group').find('input[type="text"],input[type="email"],input[type="password"],input[type="file"]').length){var classAdd='';if($(element).closest('.form-group').find('label').length==0){classAdd='input-without-label';}
$(element).closest('.form-group').append('<span class="icon-validate-custom fa fa-check form-control-feedback '+classAdd+'"></span>');}},submitHandler:function(form){if(isToSubmitHandler(form)){form.submit();$(form).find('[type="submit"]').each(function(){$(this).attr('disabled','disabled');});}
if($(form).attr('method')=='get'){$(form).find(":input").prop("disabled",false);}}});function isToSubmitHandler(form){var isToSubmit=true;$(form).find('[type="submit"]').each(function(){var attrDisabled=$(this).attr('disabled');if(typeof attrDisabled!==typeof undefined&&attrDisabled!==false){isToSubmit=false;}else{appendFormTokenInput(form);var is_safari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);if(is_safari){}
if($(this).is('button')&&$(this).is(':focus')){var form_action=$("<input>").attr("type","hidden").attr("name",$(this).attr('name'));$('form').append($(form_action).val($(this).attr('value')));}}});if($(form).attr('method')=='get'){$(form).find(":input").filter(function(){return!this.value;}).attr("disabled","disabled");$(form).find('input[name="tokenToValidateCustom"]').remove();}
return isToSubmit;}
$(document).on("change",".select2",function(){var formToValidate=$(this).parents('form');if(!$.isEmptyObject(formToValidate.validate().submitted)){formToValidate.validate().form();}});$(document).on('click','a[data-toggle="modal"], button[data-toggle="modal"]',function(){initializeModal($(this));});function initializeModal(elementLink){var url=elementLink.attr('href');var modalIdentificator=elementLink.data('target');var nameFunctionModal=elementLink.data('function');var modalContent=$(modalIdentificator).find('.modal-content');modalContent.html('');if(url){$.ajax({url:url}).done(function(html){modalContent.html(html);initializeMasks();if(nameFunctionModal){var functionModal=window[nameFunctionModal];functionModal();}});}
return false;}
jQuery.extend(jQuery.validator.messages,{required:"Campo obrigatório.",email:"E-mail inválido.",url:"URL inválida.",date:"Data inválida.",number:"Insira somente números",creditcard:"Cartão de crédito inválido",equalTo:"Repita o valor anterior",accept:"Extensão de arquivo inválida",maxlength:jQuery.validator.format("Insira no máximo {0} caracteres."),minlength:jQuery.validator.format("Insira no mínimo {0} caracteres."),max:jQuery.validator.format("Insira um valor menor ou igual a {0}."),min:jQuery.validator.format("Insira um valor maior ou igual a {0}."),cpfAndCnpj:"Documento inválido."});function initializeMasks(){$(".mask-credit-card").mask("9999 9999 9999 99999");$(".mask-month-year").mask("99/9999");$(".mask-date").mask("99/99/9999");$(".mask-datetime").mask("99/99/9999 - 99:99");$(".mask-datetimecomplete").mask("99/99/9999 99:99:99");$(".mask-datetimeinput").mask("99/99/9999 - 99:99:99");$(".mask-cep").mask("99999-999");$(".mask-cpf").mask("999.999.999-99");$(".mask-cnpj").mask("99.999.999/9999-99");$(".mask-celphone").mask("(99) 99999-9999");$(".mask-phone").mask("(99) 9999-9999");$(".mask-percent-allow-zero").maskMoney({allowZero:true,prefix:'',suffix:'%',allowNegative:false,thousands:'.',decimal:',',affixesStay:true});$(".mask-percent-six-decimal-allow-zero").maskMoney({allowZero:true,prefix:'',suffix:'%',allowNegative:false,thousands:'.',decimal:',',affixesStay:true,precision:6});$(".mask-percent").maskMoney({prefix:'',suffix:'%',allowNegative:false,thousands:'.',decimal:',',affixesStay:true});$(".mask-money").maskMoney({prefix:'R$ ',allowNegative:false,thousands:'.',decimal:',',affixesStay:true});$(".mask-money-allow-zero").maskMoney({allowZero:true,prefix:'R$ ',allowNegative:false,thousands:'.',decimal:',',affixesStay:true});var maskBehavior=function(val){return val.replace(/\D/g,'').length===11?'(00) 00000-0000':'(00) 0000-00009';},options={onKeyPress:function(val,e,field,options){field.mask(maskBehavior.apply({},arguments),options);}};$(".mask-phone-and-celphone").mask(maskBehavior,options);}
initializeMasks();function validCpf(strCPF){strCPF=strCPF.replace(/[^\d]+/g,'');var Soma;var Resto;Soma=0;if(strCPF=="00000000000")
return false;for(i=1;i<=9;i++)
Soma=Soma+parseInt(strCPF.substring(i-1,i))*(11-i);Resto=(Soma*10)%11;if((Resto==10)||(Resto==11))
Resto=0;if(Resto!=parseInt(strCPF.substring(9,10)))
return false;Soma=0;for(i=1;i<=10;i++)
Soma=Soma+parseInt(strCPF.substring(i-1,i))*(12-i);Resto=(Soma*10)%11;if((Resto==10)||(Resto==11))
Resto=0;if(Resto!=parseInt(strCPF.substring(10,11)))
return false;return true;}
function validCnpj(cnpj){cnpj=cnpj.replace(/[^\d]+/g,'');if(cnpj=='')
return false;if(cnpj.length!=14)
return false;if(cnpj=="00000000000000"||cnpj=="11111111111111"||cnpj=="22222222222222"||cnpj=="33333333333333"||cnpj=="44444444444444"||cnpj=="55555555555555"||cnpj=="66666666666666"||cnpj=="77777777777777"||cnpj=="88888888888888"||cnpj=="99999999999999")
return false;tamanho=cnpj.length-2;numeros=cnpj.substring(0,tamanho);digitos=cnpj.substring(tamanho);soma=0;pos=tamanho-7;for(i=tamanho;i>=1;i--){soma+=numeros.charAt(tamanho-i)*pos--;if(pos<2)
pos=9;}
resultado=soma%11<2?0:11-soma%11;if(resultado!=digitos.charAt(0))
return false;tamanho=tamanho+1;numeros=cnpj.substring(0,tamanho);soma=0;pos=tamanho-7;for(i=tamanho;i>=1;i--){soma+=numeros.charAt(tamanho-i)*pos--;if(pos<2)
pos=9;}
resultado=soma%11<2?0:11-soma%11;if(resultado!=digitos.charAt(1))
return false;return true;}
function isDateValidToBill(date){var dateArray=date.split('/');var dateObj=new Date(dateArray[2],dateArray[1],dateArray[0]);var actualDate=new Date();var actualDay=actualDate.getDate();var actualMonth=actualDate.getMonth()+1;var actualYear=actualDate.getFullYear();var dateDay=dateObj.getDate();var dateMonth=dateObj.getMonth();var dateYear=dateObj.getFullYear();if(dateYear>actualYear+10){return false;}
if(dateYear==actualYear+10){if(dateMonth>actualMonth){return false;}
if(dateDay>actualDay){return false;}}
return true;}
function isDateValidToAutomaticDebit(date,days){var dateArray=date.split('/');var dateInputObj=new Date(dateArray[2],dateArray[1],dateArray[0]);dateInputObj.setHours(0,0,0,0);var limitDate=new Date();limitDate.setDate(limitDate.getDate()+parseInt(days));limitDate.setMonth(limitDate.getMonth()+1)
limitDate.setHours(0,0,0,0);if(dateInputObj>=limitDate){return true;}
return false;}
jQuery.validator.addMethod("noWhiteSpace",function(value,element){return value.match(/^(\s)+$/);},"Não coloque espaços.");jQuery.validator.addMethod("maxDateBill",function(value,element){return isDateValidToBill(value);},"O Contrato/Venda não pode durar mais de 10 anos.");jQuery.validator.addMethod("minDateTransaction",function(value,element,dataAttr){var days=$(element).attr(dataAttr);return isDateValidToAutomaticDebit(value,days);},function(dataAttr,element){return "A data de vencimento deve ser no mínimo "+$(element).attr(dataAttr)+" dias após dia atual.";});jQuery.validator.addMethod("filesizeMax",function(value,element,param){if(element.files&&element.files.length){var file=element.files[0];return(file.size&&file.size<=param);}},function(param){var sizeMb=param/1024/1024;return 'O tamanho do arquivo excede o tamanho máximo permitido de '+sizeMb+'MB';});jQuery.validator.addMethod("cpfAndCnpj",function(r,t){var tamanho=r.length;if(tamanho<15){return validCpf(r)||this.optional(t);}else{return validCnpj(r)||this.optional(t);}});jQuery.validator.addMethod("noSpace",function(value,element){return value.indexOf(" ")<0&&value!="";},"Não informe espaços.");jQuery.validator.addMethod("minlengthLetters",function(value,element,minLenght){var valueLetters=value.replace(/\s/g,'');return valueLetters.length>=minLenght;},"Insira no mínimo {0} caracteres.");jQuery.validator.addMethod("cpf",function(r,c){for(r=jQuery.trim(r),r=r.replace(".",""),r=r.replace(".",""),cpf=r.replace("-","");cpf.length<11;)
cpf="0"+cpf;var e=/^0+$|^1+$|^2+$|^3+$|^4+$|^5+$|^6+$|^7+$|^8+$|^9+$/,f=[],a=new Number,p=11;for(i=0;i<11;i++)
f[i]=cpf.charAt(i),i<9&&(a+=f[i]*--p);for(f[9]=(x=a%11)<2?0:11-x,a=0,p=11,y=0;y<10;y++)
a+=f[y]*p--;f[10]=(x=a%11)<2?0:11-x;var t=!0;return(cpf.charAt(9)!=f[9]||cpf.charAt(10)!=f[10]||cpf.match(e))&&(t=!1),this.optional(c)||t},"Informe um CPF válido.");jQuery.validator.addMethod("cnpj",function(r,t){r=jQuery.trim(r),r=r.replace("/",""),r=r.replace(".",""),r=r.replace(".",""),r=r.replace("-","");var e,i,a,n,o,h,l,c;if(c=1,r.length<14&&r.length<15)
return this.optional(t)||!1;for(n=0;n<r.length-1;n++)
if(r.charAt(n)!=r.charAt(n+1)){c=0;break}
if(c)
return this.optional(t)||!1;for(l=r.length-2,e=r.substring(0,l),i=r.substring(l),a=0,h=l-7,n=l;n>=1;n--)
a+=e.charAt(l-n)*h--,2>h&&(h=9);if(o=2>a%11?0:11-a%11,o!=i.charAt(0))
return this.optional(t)||!1;for(l+=1,e=r.substring(0,l),a=0,h=l-7,n=l;n>=1;n--)
a+=e.charAt(l-n)*h--,2>h&&(h=9);return o=2>a%11?0:11-a%11,o!=i.charAt(1)?this.optional(t)||!1:this.optional(t)||!0},"Informe um CNPJ válido");jQuery.validator.addMethod("email",function(t,e){return this.optional(e)||/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i.test(t);},"E-mail inválido.");jQuery.validator.addMethod("phoneBr",function(value,element){value=jQuery.trim(value);value=value.replace("(","");value=value.replace(")","");value=value.replace("-","");value=value.replace(" ","");if(value==''){return true;}
var ddd=value.substr(0,2);var regExp=new RegExp("((([1,4,6,8,9][1-9])|(2[1,2,4,7,8])|(3[1,2,3,4,5,7,8])|(4[1-9])|(5[1-5])|(7[1,3,4,5,7,9])))");if(!regExp.test(ddd)){return false;}
if(value.length!==10){return false;}
return true;},"Telefone inválido.");jQuery.validator.addMethod("celphoneBr",function(value,element){value=jQuery.trim(value);value=value.replace("(","");value=value.replace(")","");value=value.replace("-","");value=value.replace(" ","");if(value==''){return true;}
var ddd=value.substr(0,2);var regExp=new RegExp("((([1,4,6,8,9][1-9])|(2[1,2,4,7,8])|(3[1,2,3,4,5,7,8])|(4[1-9])|(5[1-5])|(7[1,3,4,5,7,9])))");if(!regExp.test(ddd)){return false;}
if(value.substr(2,1)!='9'){return false;}
if(value.length!==11){return false;}
return true;},"Celular inválido.");jQuery.validator.addMethod("minPercentualValue",function(value,e,minPercentualValue){var cleanValue=value.replace(".","");cleanValue=cleanValue.replace(",",".");cleanValue=cleanValue.replace("%","");cleanValue=parseFloat(cleanValue);if(cleanValue<parseFloat(minPercentualValue)){return false;}
return true;},"Insira um valor maior que {0}%.");jQuery.validator.addMethod("maxPercentualValue",function(value,e,maxPercentualValue){var cleanValue=value.replace(".","");cleanValue=cleanValue.replace(",",".");cleanValue=cleanValue.replace("%","");cleanValue=parseFloat(cleanValue);if(cleanValue>=parseFloat(maxPercentualValue)){return false;}
return true;},"Insira um valor menor que {0}%.");jQuery.validator.addMethod("maxValueByData",function(value,e){var cleanValue=value.replaceAll(".","");cleanValue=cleanValue.replace(",",".");cleanValue=cleanValue.replace("R$","");cleanValue=cleanValue.replace(" ","");cleanValue=parseFloat(cleanValue);var maxValue=$(e).attr('data-maxvalue');if(cleanValue>parseFloat(maxValue)){return false;}
return true;},"Insira um valor menor ou igual ao disponível para saque.");function mascaraTelefone(campo){var lastKey=0;function trata(valor,isOnBlur){if(valor.length==15){return valor;}
valor=valor.replace(/\D/g,"");valor=valor.replace(/^(\d{2})(\d)/g,"($1) $2");if(isOnBlur){valor=valor.replace(/(\d)(\d{4})$/,"$1-$2");}else{valor=valor.replace(/(\d)(\d{3})$/,"$1-$2");}
return valor;};campo.onkeyup=function(evt){lastKey=(window.event)?window.event.keyCode:evt.which;};campo.oninput=function(){var code=lastKey;var valor=this.value;var isNumeric=(code<=57&&code>=48);var isKeypad=(code<=105&&code>=96);var isBackspace=code===8;var isEnter=code===13;if(isNumeric||isKeypad||isBackspace||isEnter){this.value=trata(valor,false);}};campo.onblur=function(){var valor=this.value;valor=valor.replace(/\D/g,"");if(valor.length<10){this.value="";}else{this.value=trata(this.value,true);}};campo.focusout=function(){var valor=this.value;valor=valor.replace(/\D/g,"");if(valor.length<10){this.value="";}else{this.value=trata(this.value,true);}};campo.maxLength=15;}
function initSelect2(){if(typeof $.fn.select2!='undefined'){$.fn.select2.defaults.set('language','pt-BR');if($('.select2').length){$('.select2').select2();}}}
jQuery.validator.addMethod("phoneAndCellphone",function(value,element){value=jQuery.trim(value);value=value.replace("(","");value=value.replace(")","");value=value.replace("-","");value=value.replace(" ","");if(value==''){return true;}
var ddd=value.substr(0,2);var regExp=new RegExp("((([1,4,6,8,9][1-9])|(2[1,2,4,7,8])|(3[1,2,3,4,5,7,8])|(4[1-9])|(5[1-5])|(7[1,3,4,5,7,9])))");if(!regExp.test(ddd)){return false;}
if(value.length==11){if(value.substr(2,1)!='9'){return false;}}
return true;},"Telefone inválido.");jQuery.validator.addMethod("quantityOfTransactions",function(value){if(value>100){return false;}
return true;},"Para uma quantidade de transações maior que 100 utilize a opção 'Indeterminada'.");jQuery.validator.addMethod("minInterest",function(value){value=value.replace('%','');value=value.replace('.','');value=value.replace(',','.');value=value.replace('R$ ','');value=parseFloat(value);if(value>=0.3){return true;}
return false;},"Valor mínimo permitido de 30 centavos ou 0.30%.");jQuery.validator.addMethod("dateBR",function(t,a){var r;if(10!=t.length)
return this.optional(a)||!1;var stringTotal=t,dia=stringTotal.substr(0,2),primeiraBarra=stringTotal.substr(2,1),mes=stringTotal.substr(3,2),segundaBarra=stringTotal.substr(5,1),ano=stringTotal.substr(6,4);return 10!=stringTotal.length||"/"!=primeiraBarra||"/"!=segundaBarra||isNaN(dia)||isNaN(mes)||isNaN(ano)||ano==0000||dia>31||dia==00||mes>12||mes==00?!1:(validateData(dia,mes,ano))},"Informe uma data válida");jQuery.validator.addMethod("dateAndHourBR",function(value){var values=value.split(' - ');values=values.filter(function(x){return(x!==(undefined||null||''));});var date=values['0'];var hour=values['1'];if(!validateDateBr(date)){return false;}
if(hour!=''&&hour!=undefined){if(!validateHourMinuteSeconds(hour)){return false;}}
return true;},"Informe uma data válida");function validateDateBr(value){if(10!=value.length)
return false;var stringTotal=value,dia=stringTotal.substr(0,2),primeiraBarra=stringTotal.substr(2,1),mes=stringTotal.substr(3,2),segundaBarra=stringTotal.substr(5,1),ano=stringTotal.substr(6,4);return 10!=stringTotal.length||"/"!=primeiraBarra||"/"!=segundaBarra||isNaN(dia)||isNaN(mes)||isNaN(ano)||ano==0000||dia>31||dia==00||mes>12||mes==00?!1:(validateData(dia,mes,ano))}
function validateHourMinuteSeconds(value){if(!/^\d{2}:\d{2}$/.test(value))
return false;var parts=value.split(':');if(parts[0]>23||parts[1]>59)
return false;return true;}
function validateData(dia,mes,ano){if(mes>12){return false;}
var mesesSem31=['04','06','09','11'],r;r=!0;if(jQuery.inArray(mes,mesesSem31)!='-1'){if(dia<31){r=!0;}else{r=!1;}}
if(jQuery.inArray(mes,mesesSem31)=='-1'){if(mes==02&&(dia<29||(dia==29&&(ano%4==0)))){r=!0;}else{if(mes==02){r=!1;}}}
if(ano<1900){r=!1;}
return r;}
jQuery.validator.addMethod("onlyLettersAndNumbers",function(name){if(name==""){return true;}
if(name.length>13){return false;}
var regExp=/[^A-Za-z0-9 ]/;return regExp.test(name)?false:true;},"Informe um texto válido.");jQuery.validator.addMethod("onlyLettersAndNumbersAndSpace",function(name){if(name==""){return true;}
var regExp=/[^A-Za-z0-9 ]/;return regExp.test(name)?false:true;},"Informe um texto válido, será permitido apenas letras, números e espaços.");jQuery.validator.addMethod("holderCard",function(cardHolderName){if(cardHolderName==""){return false;}
if(cardHolderName.length>50){return false;}
var regExp=/[^A-Za-z ]/;return regExp.test(cardHolderName)?false:true;},"Informe um nome válido.");jQuery.validator.addMethod("cardValidThru",function(value){if(value.length!==7){return false;}
var value=value.split('/');var month=parseInt(value['0']);var year=parseInt(value['1']);if(!validateData(1,month,year)){return false;}
var date=new Date();if(year<date.getFullYear()){return false;}
if(date.getFullYear()==year){if(month<(date.getMonth()+1)){return false;}}
return true;},"Informe uma data válida. Exemplo: 10/2035");jQuery.validator.addMethod("moneyWithSign",function(moneyValue){if(moneyValue.length>0){var money=moneyValue.replace("R$","");money=money.replace(" ","");money=money.replace(".","");money=money.replace(",",".");if(money=='0.00'){return false;}
var regex=/^\d+(?:\.\d{0,2})$/;if(regex.test(money)){return true;}}
return false;},"Valor Inválido.");jQuery.validator.addMethod("validateDiscount",function(b,a,c){var valorDesconto=b;valorDesconto=valorDesconto.replace(".","");valorDesconto=valorDesconto.replace(",",".");valorDesconto=valorDesconto.replace("R$","");valorDesconto=parseFloat(valorDesconto);var valorInicial=$(c).data('originalvalue');valorInicial=parseFloat(valorInicial);if(valorDesconto>valorInicial){return false;}
return true;},"O valor do desconto deve ser menor ou igual ao valor da cobrança.");jQuery.validator.addMethod("dateNotInPast",function(value,element){value=value.substr(0,10);var date=value.split('/').reverse().join('-');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){return false;}
var splitDate=date.split('-');var sendDate=new Date(splitDate[0],(splitDate[1]-1),splitDate[2]);sendDate.setHours(0,0,0,0);var today=new Date();today.setHours(0,0,0,0);return this.optional(element)||sendDate.getTime()>=today.getTime();},'Data necessita ser maior ou igual a hoje.');jQuery.validator.addMethod("dateFuture",function(value,element){if(value==''){return true;}
value=value.substr(0,10);var date=value.split('/').reverse().join('-');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){return false;}
var splitDate=date.split('-');var sendDate=new Date(splitDate[0],(splitDate[1]-1),splitDate[2]);sendDate.setHours(0,0,0,0);var today=new Date();today.setHours(0,0,0,0);return this.optional(element)||sendDate.getTime()>today.getTime();},'Data necessita ser maior que hoje.');jQuery.validator.addMethod("boletoMinValue",function(value,element){return checkBoletoValueIsValid(value,element)},function(param,element){return getMessageErrorBoletoValue(element);});function checkBoletoValueIsValid(value,element){if(value.length>0){var convertedValue=value.replace('.','');convertedValue=convertedValue.replace(',','.');convertedValue=convertedValue.replace('R$','');convertedValue=parseFloat(convertedValue);var maxValueBoleto=$(element).attr('data-maxValueBoleto');if(convertedValue>=5&&convertedValue<=parseFloat(maxValueBoleto)){return true;}}
return false;}
function getMessageErrorBoletoValue(element){var maxValueTreated=$(element).attr('data-maxValueBoletoTreated');var isVerifiedDocuments=$(element).attr('data-isVerifiedDocuments')=='T';if(maxValueTreated==='R$ 0,01'&&!isVerifiedDocuments){return '<p class="warning-boleto">Para emitir suas cobranças você precisa verificar sua conta, clique <a href="verificar-conta">aqui</a> para enviar seus documentos.</p>';}
return 'O valor mínimo do boleto é de R$ 5,00 e o máximo de '+maxValueTreated
+'<br> Para solicitar aumento de limite, acesse Configurações - Tarifas e Limites, '
+'<a target="_blank" href="'+URL_BASE+'tarifas-limites" class="alert-link"> <b>Clique Aqui</b></a>.';}
function treatResponseBoletoValue(param,element){var maxValueTreated=$(element).attr('data-maxValueBoletoTreated');var isVerifiedDocuments=$(element).attr('data-isVerifiedDocuments')=='T';if(maxValueTreated==='R$ 0,01'&&!isVerifiedDocuments){return '<p class="warning-boleto">Para emitir suas cobranças você precisa verificar sua conta, clique <a href="verificar-conta">aqui</a> para enviar seus documentos.</p>';}
return 'O valor mínimo do boleto é de R$ 5,00 e o máximo de '+maxValueTreated
+'<br> Para solicitar aumento de limite, envie uma '
+'<b>comprovação da necessidade</b> <b data-toggle="tooltip" title= " Exemplo: Nota fiscal/contrato assinado (recente)" class="fa fa-info-circle"></b> para '
+'<a href="mailto:analise.cel_cash@celcoin.com.br" style="color: inherit; text-decoration: underline">analise.cel_cash@celcoin.com.br </a>';}
jQuery.validator.addMethod('safePassword',function(value,element){return this.optional(element)||(value.length>=6&&(value.match(/[a-zA-Z]/)||value.match(/[0-9]/))&&value.match(/["~!@#$%^&*\(\)_+=`{}\[\]\|\\:;'<>,.\/?"\-]/));},'Informe uma senha válida.<br>Digite no mínimo 6 caracteres contendo letras e/ou números e um caracter especial.');if($('#companyForm').length==0){$(document).on('click','.sa-confirm-button-container button',function(){$(this).attr('disabled','disabled');});}
jQuery.validator.addMethod("extension",function(value,element,param){param=typeof param==="string"?param.replace(/,/g,'|'):"png|jpe?g|gif";return this.optional(element)||value.match(new RegExp(".("+param+")$","i"));},"Informe uma extensão válida");jQuery.validator.addMethod("urlComplement",function(value){if(value.match(/["~!@#$%^&*\(\)_+=` {}\[\]\|\\:;'<>,.\/?"]/)){return false;}
return(value.match(/[a-zA-Z]/)||value.match(/[0-9]/));},'Informe uma URL válida.<br>Digite apenas letras e traço(-) para separar palavras.');$('button[data-target="#image-template"], a[data-target="#image-template"]').click(function(event){var image=$(this).data('image');var modalId=$(this).data('target');$('.background-modal-template').attr('src',image);$(modalId).modal('toggle');event.preventDefault();return false;});$(document).ready(function(){if($('.ajust-height').length){$('.ajust-height').each(function(){runHeightElement($('.ajust-height'));});}
if($('form[name="custom-field-form-report"]').length){$('form[name="custom-field-form-report"]').validate();}});function runHeightElement(element){var maxHeight=0;element.each(function(){$(this).css('min-height','unset');});element.each(function(){var currentHeight=$(this).outerHeight();if(currentHeight>maxHeight){maxHeight=currentHeight;}});element.each(function(){$(this).css('min-height',maxHeight);});}
$.validator.addClassRules("noSpace",{noSpace:true});$.validator.addClassRules("onlyNumberField",{number:true});$.validator.addClassRules("requiredField",{required:true});$.validator.addClassRules("requiredFieldEmail",{required:true,email:true,validateEmailCustomErrorWithAlert:true});$.validator.addClassRules("validateEmailCustomOnlyError",{required:true,email:true,validateEmailCustomOnlyError:true});$.validator.addClassRules("minDateTransaction",{minDateTransaction:'data-daysBeforeAutomaticDebit'});$.validator.addClassRules("maxLength30",{maxlength:30});$.validator.addClassRules("maxLength60",{maxlength:60});$.validator.addClassRules("onlyLettersAndNumbers",{onlyLettersAndNumbers:true});$.validator.addClassRules("onlyLettersAndNumbersAndSpace",{onlyLettersAndNumbersAndSpace:true});$.validator.addClassRules("cpfAndCnpj",{cpfAndCnpj:true});$.validator.addClassRules("maxLength20",{maxlength:20});$.validator.addClassRules("fieldEmail",{email:true});$.validator.addClassRules("fieldUrl",{url:true});$.validator.addClassRules("fieldPhone",{phoneAndCellphone:true});jQuery.validator.addMethod("validateEmailCustomOnlyError",function(value,element,params){var validator=this;var email=$(element).val();return $.ajax({url:"validate-email-only-error",type:"post",dataType:"json",async:false,data:{email:email},success:function(data){var formGroup=$(element).parents('.form-group');if(data.type==true){return true;}else{formGroup.find('.text-success').remove();var errors={};errors[element.name]=data.msg;validator.showErrors(errors);return false;}}});},'');jQuery.validator.addMethod("validateEmailCustomErrorWithAlert",function(value,element,params){var validator=this;var email=$(element).val();return $.ajax({url:"validate-email-error-with-alert",type:"post",dataType:"json",async:false,data:{email:email},success:function(data){var formGroup=$(element).parents('.form-group');if(data.type==true){var msg='';if(data.msg.length>0){msg='<i class="fa fa-warning"></i> '+data.msg;}
if(formGroup.find('.text-warning-dark').length==0){formGroup.append('<span id="'+$(element).attr('id')+'-error" class="text-warning-dark error-validate">'+msg+'</span>');}else{formGroup.find('.text-warning-dark').html(msg);}
return true;}else{formGroup.find('.text-warning-dark').remove();var errors={};errors[element.name]=data.msg;validator.showErrors(errors);return false;}}});},'');$(document).on('click','#accordion .card-header a',function(){if($(this).find('.fa-plus, .fa-minus').length){if($(this).find('.fa-plus').length){$(this).find('.fa-plus').addClass('fa-minus').removeClass('fa-plus');}else if($(this).find('.fa-minus').length){$(this).find('.fa-minus').addClass('fa-plus').removeClass('fa-minus');}}});$(document).ready(function(){if($('.card-header a').length){var expanded=$('.card-header a').attr('aria-expanded');if(expanded=='true'){var collapse=$('.card-header a').parents('.card').find('.collapse');collapse.slideToggle('slow');}
$('.card-header a').click(function(){var expanded=$(this).attr('aria-expanded');var card=$(this).parents('.card');var cardHeader=$(this).parents('.card-header');if(cardHeader.hasClass('open')){cardHeader.removeClass('open');card.removeClass('open');}else{cardHeader.addClass('open');card.addClass('open');}
var collapse=$(this).parents('.card').find('.collapse');collapse.slideToggle('slow');});}
if($('#triggerRedirectUrl').length){var url=$('#triggerRedirectUrl').data('url');var time=$('#triggerRedirectUrl').data('ms-redirect');setTimeout(function(){window.location.href=url;},time);}});$(document).on('change','.hasZipCode input[name="zipcode"]',function(){var zipcode=$(this).val();$.ajax({url:'busca-endereco',type:'POST',dataType:'json',data:{zipcode:zipcode}}).done(function(data){$('.hasZipCode input[name="street"]').val(data.street);if($('.hasZipCode select[name="city"]').hasClass('select-city-ibge')){if($('.hasZipCode select[name="city"]').find("option[value='"+data.city+"']").length){$('.hasZipCode select[name="city"]').val(data.city).trigger('change');}else if(data.city!==null){var newOption=new Option(data.city,data.city,true,true);$('.hasZipCode select[name="city"]').append(newOption).trigger('change');}}else{$('.hasZipCode input[name="city"]').val(data.city);}
$('.hasZipCode input[name="neighborhood"]').val(data.neighborhood);var stateHasSelect2=false;if($('.hasZipCode select[name="state"]').hasClass("select2-hidden-accessible")){stateHasSelect2=true;$('.hasZipCode select[name="state"]').select2('destroy');}
$('.hasZipCode select[name="state"] option').each(function(){$(this).removeAttr('selected');});$('.hasZipCode select[name="state"]').val(data.state);$('.hasZipCode select[name="state"] option[value="'+data.state+'"]').attr('selected','selected');if(stateHasSelect2){$('.hasZipCode select[name="state"]').select2();}
if(data.street!=''){$('.hasZipCode input[name="number"]').focus();}else{$('.hasZipCode input[name="street"]').focus();}});});var emptyTextEditInline='Não preenchido';var urlUpdateCustomFieldBill='update-custom-field-bill';if($('.inline-input').length){$('.inline-input').editable({emptytext:emptyTextEditInline,url:urlUpdateCustomFieldBill,ajaxOptions:{type:'post',dataType:'json'}});}
function getParamsUrl(){var url=window.location.href;var data=url.split('?');return(data['1']==undefined?'':data['1']);}
if($('.jsonFormatter').length){$('.jsonFormatter').jsonFormatter();}
$(document).on('change','[data-alertToCheck]',function(){var text=$(this).attr('data-alerttocheck');if(text!=''&&$(this).is(':checked')){swal({type:"warning",title:"Alerta",text:text})}});function showPopupWithdrawWithError(){$.ajax({url:'show-message-popup-withdraw-withError',success:function(html){if(html){$('#myModal .modal-content').html(html);$('#myModal').modal('toggle');}}});}
$(document).on('click','input[name="email"][value="@galaxpay.com.br"]',function(){$(this).caretToStart();});$(document).on('change','.checkBoxToUpdateFile',function(){if($(this).is(':checked')){$(this).parents('.boxInputFile').find('input[type="file"]').show();}else{$(this).parents('.boxInputFile').find('input[type="file"]').hide();}});$(document).ready(function(){if($('#swal-welcome').length){swal('Bem vindo','Parabéns, seu cadastro foi realizado com sucesso, verifique seu celular e comece a emitir boletos agora mesmo =)','success');}});function applyMaskPercentOrMoneyInInputInterest(nameInput,mask,isChanged){var input=$('input[name="'+nameInput+'"]');input.rules('remove');input.rules('add',{minInterest:true});if(mask=='fixed'){input.removeClass('mask-percent-allow-zero');input.addClass('mask-money-allow-zero');input.rules('add',{diferenteDe:'R$ 0,00'});}else{input.removeClass('mask-money-allow-zero');input.addClass('mask-percent-allow-zero');input.rules('add',{maxPercentualValue:100});input.rules('remove','diferenteDe');input.rules('add',{diferenteDe:'0,00%'});}
initializeMasks();if(isChanged){input.trigger('focus');}}
function applyMaskPercentOrMoneyInInput(nameInput,mask,isChanged){var input=$('input[name="'+nameInput+'"]');input.rules('remove');if(mask=='fixed'){input.removeClass('mask-percent-allow-zero');input.addClass('mask-money-allow-zero');input.rules('add',{diferenteDe:'R$ 0,00'});}else{input.removeClass('mask-money-allow-zero');input.addClass('mask-percent-allow-zero');input.rules('add',{maxPercentualValue:100});input.rules('remove','diferenteDe');input.rules('add',{diferenteDe:'0,00%'});}
initializeMasks();if(isChanged){input.trigger('focus');}}
$(document).on('click','.dropdown-header-list',function(){$('.dropdown-menu').slideUp();var menu=$(this).find('.dropdown-menu');if(menu.is(':visible')){menu.slideUp();}else{menu.slideDown();}});$(document).on('click','.option-with-image',function(){var radio=$(this).find('input[type="radio"]');var radioName=radio.attr('name');$('input[name="'+radioName+'"]').removeAttr('checked');radio.prop('checked','checked');});$(document).on('click','a[href^="remove-history-invoice"]',function(event){event.preventDefault();var url=$(this).attr('href');swal({title:'Tem certeza que deseja excluir o histórico ?',text:'',type:"error",showCancelButton:true,cancelButtonText:"Cancelar",confirmButtonColor:"#DD6B55",confirmButtonText:"Sim, excluir",closeOnConfirm:false},function(){$.ajax({url:url,type:'POST',dataType:'json'}).done(function(data){if(data.type===true){swal('',data.msg,'success');}else{swal('',data.msg,'danger');}});});});$(document).ready(function(){$('.btns-acoes-rapidas').each(function(){var qtdButtons=$(this).find('a').length;if(qtdButtons==0){$(this).hide();}});});function replaceAccents(word){var from='áàãâäéèêëẽíìîïĩóòõöôúùûüũçÁÀÃÂÄÉÈÊËẼÍÌÎÏĨÓÒÕÖÔÚÙÛÜŨÇ';var to='aaaaaeeeeeiiiiiooooouuuuucAAAAAEEEEEIIIIIOOOOOUUUUUC';var response='';for(var i=0;i<word.length;i++){if(from.search(word.substr(i,1))>=0){response+=to.substr(from.search(word.substr(i,1)),1);}else{response+=word.substr(i,1);}}
return response;}
$(document).on('click','a[href^="exportar-excel/"]',function(event){event.preventDefault();var url=$(this).attr('href');var limit=$(this).attr('limit-export');var isAdmin=$(this).attr('data-is-admin');if(isAdmin){$.ajax({url:'get-form-reason-to-export'}).done(function(form){alertExcel(url,limit,form);});}else{alertExcel(url,limit,'');}});function alertExcel(url,limit,form){swal({title:'Tem certeza que deseja realizar a exportação para Excel?',text:'* Serão exportados no máximo '+limit+' registros'+form,type:"warning",showCancelButton:true,cancelButtonText:"Cancelar",confirmButtonColor:"#f29a3e",confirmButtonText:"Sim, exportar.",showLoaderOnConfirm:true,closeOnConfirm:false},function(){generateFileExport(url);});}
$(document).on('click','a[href^="exportar-csv/"]',function(event){event.preventDefault();var url=$(this).attr('href');var limit=$(this).attr('limit-export');var isAdmin=$(this).attr('data-is-admin');if(isAdmin){$.ajax({url:'get-form-reason-to-export'}).done(function(form){alertCsv(url,limit,form);});}else{alertCsv(url,limit,'');}});function alertCsv(url,limit,form){swal({title:'Tem certeza que deseja realizar a exportação para CSV?',text:'* Serão exportados no máximo '+limit+' registros'+form,type:"warning",showCancelButton:true,cancelButtonText:"Cancelar",confirmButtonColor:"#f29a3e",confirmButtonText:"Sim, exportar.",showLoaderOnConfirm:true,closeOnConfirm:false},function(){generateFileExport(url);});}
$(document).on('click','a[href^="exportar-pdf/"]',function(event){event.preventDefault();var url=$(this).attr('href');var limit=$(this).attr('limit-export');var isAdmin=$(this).attr('data-is-admin');if(isAdmin){$.ajax({url:'get-form-reason-to-export'}).done(function(form){alertPdf(url,limit,form);});}else{alertPdf(url,limit,'');}});function alertPdf(url,limit,form){swal({title:'Tem certeza que deseja realizar a exportação para PDF?',text:'* Serão exportados no máximo '+limit+' registros'+form,type:"warning",showCancelButton:true,cancelButtonText:"Cancelar",confirmButtonColor:"#f29a3e",confirmButtonText:"Sim, exportar.",showLoaderOnConfirm:true,closeOnConfirm:false},function(){generateFileExport(url);});}
$(document).on('click','a[href^="exportar-process"]',function(event){event.preventDefault();var url=$(this).attr('href');var type=$(this).attr('type');alertProcess(url,type);});function alertProcess(url,type){swal({title:'',text:'Deseja prosseguir com a exportação dos dados no formato '+type.toUpperCase()+'?',type:"warning",showCancelButton:true,cancelButtonText:"Cancelar",confirmButtonColor:"#f29a3e",confirmButtonText:"Sim, exportar.",showLoaderOnConfirm:true,closeOnConfirm:false,},function(){generateFileExportInEmail(url);});}
function generateFileExport(url){$.ajax({url:url,type:'post',data:$('#form-reasons-in-alert').serialize(),dataType:'json'}).done(function(data){if(data.type===true){location.href=data.msg;swal('','Arquivo gerado com sucesso!','success');}else{swal('',data.msg,'danger');}});}
function generateFileExportInEmail(url){$.ajax({url:url,type:'post',dataType:'json'}).done(function(data){if(data.type===true){swal({title:'Sucesso',text:'O seu arquivo está sendo processado e será enviado para o seu e-mail em alguns minutos.',type:"success",showCancelButton:false,showConfirmButton:true,});}else{swal({title:'',text:data.msg,type:'error',allowOutsideClick:false,confirmButtonText:'Ok'});}});}
function maskPhoneAndCelphone(campo){var lastKey=0;function trata(valor,isOnBlur){valor=valor.replace(/\D/g,"");valor=valor.replace(/^(\d{2})(\d)/g,"($1) $2");valor=valor.replace(/(\d)(\d{4})$/,"$1-$2");return valor;};campo.onkeyup=function(evt){lastKey=(window.event)?window.event.keyCode:evt.which;console.log(lastKey);};campo.oninput=function(){var code=lastKey;var valor=this.value;var isNumeric=(code<=57&&code>=48);var isKeypad=(code<=105&&code>=96);var isBackspace=code===8;var isEnter=code===13;if(isNumeric||isKeypad||isBackspace||isEnter){this.value=trata(valor,false);}};campo.onblur=function(){var valor=this.value;valor=valor.replace(/\D/g,"");if(valor.length<10){this.value="";}else{this.value=trata(this.value,true);}};campo.focusout=function(){var valor=this.value;valor=valor.replace(/\D/g,"");if(valor.length<10){this.value="";}else{this.value=trata(this.value,true);}};campo.maxLength=15;}
if(typeof URL_BASE!='undefined'){$.LoadingOverlaySetup({image:URL_BASE+"view/images/loading2.gif",zIndex:998});}
function isDateVigencyValidPayday(date,payday){if(date===''){return true;}
var dateArray=date.split('/');var dateInputObj=new Date(dateArray[2],dateArray[1],dateArray[0]);dateInputObj.setHours(0,0,0,0);var paydayArray=payday.split('/');var limitDate=new Date(paydayArray[2],paydayArray[1],paydayArray[0]);limitDate.setHours(0,0,0,0);limitDate.setHours(0,0,0,0);return(dateInputObj<limitDate);}
jQuery.validator.addMethod("vigencyDate",function(value,element){var payday=$('input[name="payDayTransaction"]').val();return isDateVigencyValidPayday(value,payday);},"A data de início de vigência deve ser menor do que a data de vencimento da 1ª transação.");jQuery.validator.addMethod("minValueByData",function(value,element){if(value.length>0){var convertedValue=value.replace('.','');convertedValue=convertedValue.replace(',','.');convertedValue=convertedValue.replace('R$','');convertedValue=parseFloat(convertedValue);var minValue=$(element).attr('data-minValueMoney');var convertedMinValue=minValue.replace(',','.');convertedMinValue=convertedMinValue.replace('R$','');convertedMinValue=parseFloat(convertedMinValue);if(convertedValue>=convertedMinValue){return true;}}
return false;},function(param,element){var maxValueTreated=$(element).attr('data-minValueMoney');return 'O valor mínimo deste campo é '+maxValueTreated;});jQuery.validator.addMethod("maxValueByDataReverse",function(value,element){if(value.length>0){var convertedValue=value.replaceAll('.','');convertedValue=convertedValue.replaceAll(',','.');convertedValue=convertedValue.replaceAll('R$','');convertedValue=parseFloat(convertedValue);var minValue=$(element).attr('data-maxValueMoneyReverse');var convertedMinValue=minValue.replaceAll('.','');convertedMinValue=convertedMinValue.replaceAll(',','.');convertedMinValue=convertedMinValue.replaceAll('R$','');convertedMinValue=parseFloat(convertedMinValue);if(convertedValue<=convertedMinValue){return true;}}
return false;},function(param,element){var maxValueTreated=$(element).attr('data-maxValueMoneyReverse');return 'O valor máximo disponível para solicitar o estorno é  de '+maxValueTreated;});jQuery.validator.addMethod("minValueByDataReverse",function(value,element){if(value.length>0){var convertedValue=value.replaceAll('.','');convertedValue=convertedValue.replaceAll(',','.');convertedValue=convertedValue.replaceAll('R$','');convertedValue=parseFloat(convertedValue);var minValue=$(element).attr('data-minValueMoneyReverse');var convertedMinValue=minValue.replaceAll('.','');convertedMinValue=convertedMinValue.replaceAll(',','.');convertedMinValue=convertedMinValue.replaceAll('R$','');convertedMinValue=parseFloat(convertedMinValue);if(convertedValue>=convertedMinValue){return true;}}
return false;},function(param,element){var minValueTreated=$(element).attr('data-minValueMoneyReverse');return 'O valor mínimo disponível para solicitar o estorno é de '+minValueTreated;});function readOnlySelect(select){select.css({'background':'#eee','pointer-events':'none','touch-action':'none'});select.prop('readonly','readonly');select.prop('tabindex','-1');}
$('input.mask-cpf-and-cnpj').keyup(function(){let input=$(this);let value=input.val();let lenght=value.length;input.attr('maxlength',18);input.rules('add',{cpfAndCnpj:true});if(lenght<15){input.val(maskCpfInputValue(value));}else{input.val(maskCnpjInputValue(value));}});function maskCpfInputValue(valor){valor=valor.replace(/\D/g,'');valor=valor.replace(/(\d{3})(\d)/,"$1.$2");valor=valor.replace(/(\d{3})(\d)/,"$1.$2");valor=valor.replace(/(\d{3})(\d{2})$/,"$1-$2");return valor;}
function maskCnpjInputValue(valor){valor=valor.replace(',','.');valor=valor.replace(/\D/g,'');valor=valor.replace(/^(\d{2})(\d)/,"$1.$2");valor=valor.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3");valor=valor.replace(/\.(\d{3})(\d)/,".$1/$2");valor=valor.replace(/(\d{4})(\d)/,"$1-$2");return valor;}